### ISSUE TITLE
ignoreCSS Selectors Do NOT Work Dynamically without Calling table.reset()

### ISSUE THREAD

**Issue by own3mall** [clarketm/TableExport#144]
I'm using the latest version of TableExport v5 with jQuery 3.x.

When using the below ignoreCSS setting, if I dynamically add or remove the defined classes to specific `<th>` and `<td>` columns, the columns are not ignored properly unless I call `table.reset()` after adding or removing these classes using a toggle column control I created.  I would assume that when the export function is called, it should recheck all the columns again without me having to reset anything and determine whether or not it should be ignored based on its classname. 

```
TableExport.prototype.ignoreCSS = [".hide", ".noExcel"];
```

**Comment by dagang007** [comment]
Hi ! Do you know where to set datetime format ? My question is just beside yours ( No.69 )

**Comment by clarketm** [comment]
@own3mall – the parsing process is a rather heavy, high time-complexity operation since, on the client-side, it must parse arbitrarily large tables in up 4 different file formats. For this reason, the parsed output is generated one time on the execution of `TableExport` and does not dynamically update unless explicitly told to with a call to `reset`. Unfortunately, unlike React there is no diff algorithm to detect changes in `TableExport`.

**Comment by own3mall** [comment]
Ok, no problem.  Thanks for looking into it.
