### ISSUE TITLE
Arabic language 

### ISSUE THREAD

**Issue by ahmedalmulki** [clarketm/TableExport#38]
Hi and thanks for this nice plugin , everything worked perfect except when I have some fields with Arabic language the excel file will read this Arabic words like "Ø§Ù„Ø¹Ø¨Ø±ÙŠØ©" , please is there any way to solve this problem ,
Thanks again.

**Comment by clarketm** [comment]
@ahmedalmulki – thanks for your interest in [TableExport](https://github.com/clarketm/TableExport).

Please help me better understand the context by answering a few questions, then I will try to get the issue resolved:

- [ ] Which file formats display the improper Arabic transcoding? (e.g. `.xlsx`, `.xls`, or both)
- [ ] What OS are you using? (e.g. `OS X 11.11`)
- [ ] What version of Excel are you using (e.g. `Excel Mac 2011`)?

**Comment by ahmedalmulki** [comment]
@clarketm - thanks for your support 

- .xls
- windows 10
- office 2010

**Comment by clarketm** [comment]
There may be compatibility issues (or just warnings) with older versions of Excel and `xls`. If that is the case, then it would be an issue with either a) my implementation or b) the dependency of [SheetJS]() which handles the parsing. I have performed multiple iterations of testing with [v4.0.0](https://github.com/clarketm/TableExport/releases/tag/v4.0.0) (latest release) with positive results. If this is not the case for you with the latest release please reply back and let me know.

**Comment by clarketm** [comment]
This is **fixed**, **verified**, and **tested** with the `xlsx` filetype in Excel. If any issues arise or more context is provided, then we can reopen.

**Comment by saidbakr** [comment]
The issue is still exist. In both version 4.x and 5.x. First of all I'm using Ubuntu linux 64 bit 16.04, Chrome browser 67.0.3396.62 (Official Build) (64-bit) and LibreOffice Calc Version: 5.1.6.2.
I will try to show the issue using screen shots from the browser and the Calc, then I will show you the code:
From Browser:
![tx1](https://user-images.githubusercontent.com/467554/40997365-a90018a0-6904-11e8-975a-a0a01531bae2.png)

From Calc as csv
![tx2](https://user-images.githubusercontent.com/467554/40997454-0c2729c8-6905-11e8-8d60-2d4c41e4d915.png)

From Calc as xlsx
![tx3](https://user-images.githubusercontent.com/467554/40997609-9722e990-6905-11e8-833e-a4d49c2e566f.png)
Also I added xls:
![tx4](https://user-images.githubusercontent.com/467554/40997737-f77fc45c-6905-11e8-87c3-86c9d8920e8b.png)

The following is the code that I have used in laravel blade, where variables inside `{{}}` to generalize the usage and there is no any errors from the browser's console.:

```
<link rel='stylesheet' type='text/css' property='stylesheet' href="/js/table_export/tableexport.min.css?ver={{config('fox.cssver')}}" />
<script src="/js/table_export/xlsx.core.min.js"></script>
<script src="/js/table_export/Blob.min.js"></script>
<script src="/js/table_export/FileSaver.min.js"></script>
<script src="/js/table_export/tableexport.min_.js"></script>
<script>
TableExport.prototype.xlsx = {
    defaultClass: "xlsx",
    buttonContent: "{{__('Export to')}}"+" xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    fileExtension: ".xlsx"
    
    
};
TableExport.prototype.xls = {
    defaultClass: "xls",
    buttonContent: "{{__('Export to')}}"+" xls",
    separator: "\t",
    mimeType: "application/vnd.ms-excel",
    fileExtension: ".xls"
};
/* Comma Separated Values (.csv) */
TableExport.prototype.csv = {
    defaultClass: "csv",
    buttonContent: "{{__('Export to')}}"+" csv",
    separator: ",",
    mimeType: "application/csv",
    fileExtension: ".csv"
};
/* Plain Text (.txt) */
TableExport.prototype.txt = {
    defaultClass: "txt",
    buttonContent: "{{__('Export to')}}"+" txt",
    separator: "  ",
    mimeType: "text/plain",
    fileExtension: ".txt"
};
TableExport.prototype.charset = "charset=utf-8";
$("{{$EXPT_selector}}").tableExport({
    filename: "{{$EXPT_filename}}_{{date('Y_m_d_H')}}",
    formats: ['csv','xlsx', 'xls'], //['xlsx','xls', 'csv', 'txt']
    
    headers: true,
    bootstrap: true,
    position: 'top',
    ignoreRows: {{$EXPT_ignoreRows}},           
    ignoreCols: {{$EXPT_ignoreCols}}, 
    trimWhitespace: true
});
</script>
```
