### ISSUE TITLE
The export does not work on IE

### ISSUE THREAD

**Issue by CrestApps** [clarketm/TableExport#43]
When using this plugin with IE it does not work.

I even tried using the live-demo you have on your website with IE 11 but nothing happens when I hit download

This is the link I tried to export from using IE 11.

https://www.travismclarke.com/tableexport/#live-demo

**Comment by aflores** [comment]
+1 - I think is because the saveAs method is not available in TableExport but I do not know why. Might hove to do with the order the files are included or the way 'msSaveOrOpenBlob' is used

**Comment by clarketm** [comment]
@CrestApps   – thanks for your interest in [TableExport](https://github.com/clarketm/TableExport).

Please help me better understand the context by answering a few questions, then I will try to get the issue resolved:

- [ ] Which file formats do **not** work in IE 11? (e.g. `.xlsx`, `.xls`, `.csv`, `.txt`)
- [ ] Are you getting any error in the browser console?

> I recently uploaded the latest source to my server where I am hosting [TableExport](https://github.com/clarketm/TableExport) to rule out stale code/dependencies as the culprit.

**Comment by aflores** [comment]
In my case is the format that I need is xlsx so that is the only one I have tested. The error I see is that 'saveAs' is null. I am calling export2file directly as I need to use my own UI.
I do not have access to windows now so I cannot recreate the problem to provide more information.
I will get back to you later.

Thanks for your work.

**Comment by CrestApps** [comment]
@clarketm all formats do not work with IE. When I visit https://www.travismclarke.com/tableexport/#live-demo with IE and try to click on any of the export button (i.e. xlsx, xls, csv, txt) nothing happens. Also, I get no errors in the console command.

I hope this helps.

**Comment by aflores** [comment]
For now, the following hack works for me:

Insert the following code before line 505 of version 3.3.9 (this will resolve the reference to msSaveOrOpenBlob)

```javascript
            // IE 10+ (native saveAs)
            // saveAs should come from FileSaver but this should help resolve the reference for now
            if (typeof saveAs === "undefined" && typeof navigator !== "undefined" && navigator.msSaveOrOpenBlob) {

                saveAs = function (blob, name, no_auto_bom) {
                    navigator.msSaveOrOpenBlob(blob, name);
                }
            }
```

**Comment by zalenix** [comment]
I added a pull request to address IE support: https://github.com/clarketm/TableExport/pull/49

**Comment by clarketm** [comment]
Thanks all (@aflores, @zalenix @CrestApps).

**Comment by clarketm** [comment]
As @aflores mentioned - fundamentally, the issue is with *either* [filesaver](https://github.com/clarketm/FileSaver.js/blob/master/FileSaver.js) **OR** my implementation/integration of filesaver because there is a logical gate to catch and handle this in filesaver (see image below). Before I *transfer* this issue over to that repo, let me rule out first that the issue isn't the latter (TableExport's implementation).

<img width="621" alt="screen shot 2017-04-28 at 1 55 04 pm" src="https://cloud.githubusercontent.com/assets/9957358/25547048/57ff2bb2-2c1a-11e7-9ec4-a9ce8553c656.png">

**Comment by clarketm** [comment]
I am limited on IE-based testing tools at the moment but a quick check over on `BrowserStack` rendered positive results on **Win 7 - IE11**:

![bs_win7_ie_11 0](https://cloud.githubusercontent.com/assets/9957358/25548392/f2de2e16-2c20-11e7-95fd-d590490de926.jpg)

**Comment by clarketm** [comment]
This has now been patch over in [FileSaver.js](https://github.com/clarketm/FileSaver.js) [v1.3.6](https://github.com/clarketm/FileSaver.js/releases/tag/v1.3.6)

**Comment by subrat7** [comment]
Hi tableexport.js is unable to export multiple sheet on IE 10+,please help me
I am getting below error

![image](https://user-images.githubusercontent.com/12031027/36260624-ff9dff3e-1287-11e8-9933-423b532a0597.png)

![image](https://user-images.githubusercontent.com/12031027/36260661-16d16b50-1288-11e8-9c2a-7d0d754b1a1f.png)
