### ISSUE TITLE
Exporting TableSorter Data (TFooter & Filter Exclusion)

### ISSUE THREAD

**Issue by JamoCA** [clarketm/TableExport#5]
Is there any way to identify elements that should be ignored?  I use TableSorter and currently the tfoot (added prior to tbody), filter & pagination header rows are included in the export.

I believe that TableSorter adds a `tablesorter-ignoreRow` class to rows that should be ignored, but it'd be nice to specify TR classes that should be ignore from the generated export.

Tfoot is normally added above the tbody and is a simple repeat of the thead. Using TableExport results in generating a double header (separated by an empty row for the dynamic filters).  Any way to ignore this?

**Comment by clarketm** [comment]
JamoCA,

Thanks for the feedback. Your reported issues are all viable candidates for
a rewrite/patch. I can agree that an ignoreRow property is a robust
extensibility and customizability addition to the plugins feature set. I
also like the idea of controlling the export download via interception
(jQuery in this case). Regarding the MIME type and susequent browser
dowload respose, can you clarify which browsers (and versions) you were
experiencing issues with.

Travis Clarke

Is there any way to identify elements that should be ignored? I use
TableSorter and currently the tfoot (added prior to tbody), filter &
pagination header rows are included in the export.

I believe that TableSorter adds a tablesorter-ignoreRow class to rows that
should be ignored, but it'd be nice to specify TR classes that should be
ignore from the generated export.

Tfoot is normally added above the tbody and is a simple repeat of the
thead. Using TableExport results in generating a double header (separated
by an empty row for the dynamic filters). Any way to ignore this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/clarketm/TableExport/issues/5>

**Comment by clarketm** [comment]
JamoCa,

Please check out my latest [v3.2.0 release] (https://github.com/clarketm/TableExport/releases/tag/v3.2.0). 

I added several new properties to the plugin. The `ignoreRows` and `ignoreCols` properties allow you to exclude rows or columns by index number (or an array of indices). Furthermore, I added a `footers` property; this, along with the `headers` property, allows you to have complete control over the filtration for both the `<tfoot>` and `<thead>` semantic tags.

In the next patch, I will add a property that allows for filtration by *selector* ... such as *class* or *id*.
