### ISSUE TITLE
Possible to export hidden rows?

### ISSUE THREAD

**Issue by Broham** [clarketm/TableExport#51]
Looking at the docs I see that you can specify `ignoreCSS` and `ignoreRows`.  I haven't entered values for either of these but when I export my table, rows that have `display:none` set are not being exported.  It looks like the default value for `ignoreCSS` is `tableexport-ignore`, but I don't have that set anywhere either.

How can I export rows that have `display:none` set?

**Comment by clarketm** [comment]
@Broham - I get what you are saying, but it, in a way, conflicts with the original purpose of the library which was to export "what you see" for usage with simple spreadsheeting and analytical tools. It would require a bit of a rewrite (which may be feasible with the [`alpha`](https://github.com/clarketm/TableExport/releases/tag/v4.0.0-alpha.4) channel that I am working on). This main channel is coupled to jQuery and although it would technically be possible, I don't know if it is the best solution. The first, and simplest, workaround would be to use `visibility:hidden` rather than `display:none`. Since `TableExport` is using jQuery's `find()` method we could in theory just add `:hidden` to the selector, but it might break some of the other show/hide logic being used with, like you mentioned, `ignoreRows` and `ignoreRows`.
