### ISSUE TITLE
Export table with data via JSON URL

### ISSUE THREAD

**Issue by slowaways** [clarketm/TableExport#55]
I am currently working with a table of over 1000 rows and 1000 columns. I am loading the rows of this table by JSON using the Bootstrap table extension: https://github.com/wenzhixin/bootstrap-table.
It's very hard for the browser to render the data from the HTML table and put it in the `data-fileblob` attribute every time I change the size of rows per page or refresh this huge table dynamically.
Is it possible to point table data via URL in settings to use remote JSON?

My Bootstrap Table Extension code:
```
    $table.bootstrapTable({
        url: '/result/data/',

        // Pagination
        pagination: true,
        pageSize: 100,
        pageList: [100, 500, 1000],
        sidePagination: 'server'

        // Toolbar
        toolbar: '#toolbar',
        showRefresh: true,
        showColumns: true,

        onLoadSuccess: function(data){
            // $table.tableExport.export(data); ?
            $("caption.btn-toolbar").remove();
            $table.tableExport({
                formats: ["xlsx"],
                position: "top"
            });
        }
    });
```
(Sorry my bad english. I'm brazilian)

**Comment by clarketm** [comment]
@slowaways - unfortunately, this is not possible with `TableExport` out-of-the-box. To be honest, `TableExport`, and client-side parsing, blobs, etc. in general, is not the most performant; it would be interesting to see benchmarks for a feature such as this after it is implemented. 

> Just to make sure I understand exactly what you are requesting, you basically want to, instead of parsing the table and saving the blob directly to the DOM element, have the ability to export to an external file and, when the user wants to export the table read the data from the file? 

As it stands, `TableExport` is a strict client-side library and I might have trouble justifying file writing from the browser. Better would be something like [`LocalStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) writing. 

If we start talking server-side, with `Node` for example, this would be more than feasible, but then we would be talking about a separate release channel.

Let me benchmark the potential performance improvements using some of the popular JS Storage APIs like `LocalStorage`, `IndexedDB`, etc. and see what sort of performance boost we can achieve. What it be possible to share your source code or at least some of the raw data you are working with so that I can get a realistic sample for testing?

**Comment by slowaways** [comment]
There are currently 1116 lines and 1031 columns. My JSON data contain sensitive data of users as passwords, identity documents number, etc. and are data of research scientific. I can't share it.

I replace your library for another called DataTables because is more faster to export:
https://datatables.net/extensions/buttons/examples/styling/bootstrap.html

**Comment by clarketm** [comment]
Thanks for the quick response and detailed explanation. DataTables is a good full-featured library, and perfect for your use-case.
