### ISSUE TITLE
Trailing new line is causing a new row in excel to be created.

### ISSUE THREAD

**Issue by CrestApps** [clarketm/TableExport#70]
I have a report that I generate using a basic HTML table. However, when my cell ends with `\r\n` for some reason the plugin does not remove that ending special new line causing the exported file to show a new line.

Here is an example of my data

`<tr><td>This is a test \r\n</td></tr>`

The above line causes the excel file to show a new row.

From the doc, the option `trimWhitespace` should be set to true to fix this problem. 

I think there are two issues here;  first in the docs and another in the functionality. 

The docs say that the default value for `trimWhitespace`  is false but from reading the code it seems to be set to `true`. This line show that it is set to true by default. https://github.com/clarketm/TableExport/blob/master/dist/js/tableexport.js#L167

The second issue is with the function, setting `trimWhitespace`  to true is not trimming `\r\n`. When briefly looking over the code, I see that you are calling the `String.trim()` method, https://github.com/clarketm/TableExport/blob/master/dist/js/tableexport.js#L442-L449 which for some reason is failing. The only thing that I can think about here is that you are passing `<tr><td>This is a test \r\n</td></tr>` or `<td>This is a test \r\n</td>` to the formatValue function which is why it is not trimming it correctly.

Thank you

**Comment by clarketm** [comment]
@CrestApps – I have an idea of what the problem might be, but to be certain and ensure that I  understand the context, can you please provide me the **version** of `TableExport` you are using, the errant *browser/OS*, and whether this is `xls` or `xlsx` format. I presume you are using `xls` format *without* the `xlsx` dependency since it appears that the rogue `\r\n` in the `html` text is introducing a conflict with the row delimiter (`rowDel`) used for the text-based formats (i.e. `csv`, `txt`, ... and `xls` when [SheetJS `xlsx`](https://tableexport.v4.travismclarke.com/#add-ons) is not loaded). 

![image](https://user-images.githubusercontent.com/9957358/27062029-2180c69e-4f9d-11e7-9311-78106e59334d.png)

Line breaks in `html` should [**NOT** be denoted explicitly using `\n` or `\r\n` the same was as they are in strings](https://stackoverflow.com/questions/39325414/line-break-in-html-with-n), but rather, expressed with either HTML *entities* or *tags* (e.g. `&#10;` Line Feed and `&#13;` Carriage return **OR** `<br>` tag). At least I know this is the case with most modern browsers like Chrome. This change would *instantly* fix the problem if my diagnosis was correct.

Additionally, adding the [SheetJS `xlsx`](https://tableexport.v4.travismclarke.com/#add-ons) dependency should also fix the problem (assuming you are using [v4](https://github.com/clarketm/TableExport/releases/tag/v4.0.10)).

===

Lastly, sorry if the multiple doc versions caused confusion. Only `v3` and earlier has a default `trimWhitespace` or `false`. [v4](https://github.com/clarketm/TableExport/releases/tag/v4.0.10), the [v4 docs](https://tableexport.v4.travismclarke.com/#tableexport), and the [examples](https://tableexport.v3.travismclarke.com/examples/whitespace.html) specify that `trimWhitespace` has a default value of `true`.

**Comment by CrestApps** [comment]
Sorry I missed placing the version in the issue body. 

I am using v4.0.4. And I testing using the latest version of Firefox. 

I am exporting as .xls and I am not using the xlsx extension as I want to keep my resources down to the bare min

**Comment by clarketm** [comment]
@CrestApps
It appears that you are 100% correct regarding `trimWhitespace` not applying for `xls` (when SheetJS `xlsx` is not used). This was fixed in [`v5`](https://github.com/clarketm/TableExport/releases/tag/v5.0.0-rc.8), but since I have not released a stable v5 release yet, I don't want to force you to upgrade. Instead, I have published a [patch](https://github.com/clarketm/TableExport/blob/4.x.x/dist/js/tableexport.js#L438) version [`v4.0.11`](https://github.com/clarketm/TableExport/releases/tag/v4.0.11).

> **Note:**
> Branch: [`4.x.x`](https://github.com/clarketm/TableExport/tree/4.x.x) -> v4
> Branch: [`master`](https://github.com/clarketm/TableExport/tree/master) -> v5-rc

**Comment by CrestApps** [comment]
Thanks for fixing that so quick.

When using V4.0.11, after clicking on export, I get the following error in the console and nothing is exported `TypeError: r is not a function[Learn More]`

**Comment by CrestApps** [comment]
Thanks for fixing that so quick.

I confirm that everything is working
